<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $faker = Faker::create();
        // \App\Models\User::factory(10)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);
        DB::table('convenios')->insert([
            [
                'nome' => 'Particular',
                'cnpj' => null,
                'ans' => null,
                'cep' => null,
                'rua' => null,
                'bairro' => null,
                'cidade' => null,
                'uf' => null,
                'numero' => null,
                'complemento' => null,
                'telefone' => null,
                'celular' => null,
                'deleted_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'operadora' => null
            ],
            [
                'nome' => 'Amil',
                'cnpj' => null,
                'ans' => '00001',
                'cep' => '41254458',
                'rua' => 'Alameda Ednaldo Santos de Jesus',
                'bairro' => 'São Rafael',
                'cidade' => 'Salvador',
                'uf' => 'BA',
                'numero' => '87',
                'complemento' => null,
                'telefone' => '71986082537',
                'celular' => '2',
                'deleted_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'operadora' => '123'
            ],
        ]);

        DB::table('permisoes')->insert([
            ['cargo' => 'Medico'],
            ['cargo' => 'Recepção'],
            ['cargo' => 'Admin'],
        ]);
        DB::table('tipo_profs')->insert([
            ['nome' => 'Medico'],
            ['nome' => 'Recepção'],
        ]);

        DB::table('especialidades')->insert([
            ['especialidade' => 'Clínico Geral', 'conselho' => 'CRM'], // Código 06
            ['especialidade' => 'Ginecologia', 'conselho' => 'CRM'], // Código 06
            ['especialidade' => 'Pediatria', 'conselho' => 'CRM'], // Código 06
            ['especialidade' => 'Ortopedia', 'conselho' => 'CRM'], // Código 06
            ['especialidade' => 'Cardiologia', 'conselho' => 'CRM'], // Código 06
            ['especialidade' => 'Dermatologia', 'conselho' => 'CRM'], // Código 06
            ['especialidade' => 'Oftalmologia', 'conselho' => 'CRM'], // Código 06
            ['especialidade' => 'Psiquiatria', 'conselho' => 'CRM'], // Código 06
            ['especialidade' => 'Neurologia', 'conselho' => 'CRM'], // Código 06
            ['especialidade' => 'Radiologia', 'conselho' => 'CRM'], // Código 06
            ['especialidade' => 'Urologia', 'conselho' => 'CRM'], // Código 06
            ['especialidade' => 'Geriatria', 'conselho' => 'CRM'], // Código 06
            ['especialidade' => 'Fisioterapia', 'conselho' => 'CREFITO'], // Código 05
            ['especialidade' => 'Odontologia', 'conselho' => 'CRO'], // Código 08
            ['especialidade' => 'Nutrição', 'conselho' => 'CRN'], // Código 07
            ['especialidade' => 'Psicologia', 'conselho' => 'CRP'], // Código 09
            ['especialidade' => 'Enfermagem', 'conselho' => 'COREN'], // Código 02
            ['especialidade' => 'Fonoaudiologia', 'conselho' => 'CRFA'], // Código 04
            ['especialidade' => 'Assistência Social', 'conselho' => 'CRAS'], // Código 01
            ['especialidade' => 'Farmácia', 'conselho' => 'CRF'], // Código 03
        ]);


        DB::table('profissionals')->insert([
            [
                'name' => 'Eduardo Lisboa Ferreira',
                'sobrenome' => 'Souza',
                'email' => 'admin@anb.com',
                'nasc' => $faker->date($format = 'Y-m-d', $max = 'now'),
                'cpf' => '123.123.123-12', // CPF gerado manualmente
                'cep' => $faker->postcode,
                'rua' => $faker->streetAddress,
                'bairro' => $faker->streetName,
                'cidade' => $faker->city,
                'uf' => $faker->stateAbbr,
                'numero' => $faker->buildingNumber,
                'complemento' => $faker->secondaryAddress,
                'telefone' => $faker->phoneNumber,
                'celular' => '(71) 98608-2537',
                'genero' => 'M',
                'rg' => '123.123.123.12',
                'cor' => 'Branco',
                'tipoprof_id' => 1,
                'uf_conselho_1' => 'BA',
                'uf_conselho_2' => 'BA',
                'conselho_1' => 123,
                'conselho_2' => 123,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'cbo' => '123',
                'imagem' => null,
                'permisoes_id' => null,
                'especialidade_id' => null,
                'valor' => null,
                'porcentagem' => null,
                'material' => null,
                'medicamento' => null,
                'inihonorariomanha' => null,
                'interhonorariomanha' => null,
                'fimhonorariomanha' => null,
                'inihonorarionoite' => null,
                'interhonorarionoite' => null,
                'fimhonorarionoite' => null,
            ],
            [
                'name' => 'Recepcao',
                'sobrenome' => 'Silva',
                'email' => 'cando@gmail.com',
                'nasc' => $faker->date($format = 'Y-m-d', $max = 'now'),
                'cpf' => '123.123.123-12', // CPF gerado manualmente
                'cep' => $faker->postcode,
                'rua' => $faker->streetAddress,
                'bairro' => $faker->streetName,
                'cidade' => $faker->city,
                'uf' => $faker->stateAbbr,
                'numero' => $faker->buildingNumber,
                'complemento' => $faker->secondaryAddress,
                'telefone' => $faker->phoneNumber,
                'celular' => '(71) 98608-2537',
                'genero' => 'F',
                'rg' => '123.123.123.12',
                'cor' => 'Branco',
                'tipoprof_id' => null,
                'uf_conselho_1' => null,
                'conselho_1' => null,
                'uf_conselho_2' => null,
                'conselho_2' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                // Definir como null os campos que não possuem valores para todos os registros
                'cbo' => '123',
                'imagem' => null,
                'permisoes_id' => null,
                'especialidade_id' => null,
                'valor' => null,
                'porcentagem' => null,
                'material' => null,
                'medicamento' => null,
                'inihonorariomanha' => null,
                'interhonorariomanha' => null,
                'fimhonorariomanha' => null,
                'inihonorarionoite' => null,
                'interhonorarionoite' => null,
                'fimhonorarionoite' => null,
            ]
        ]);

        DB::table('especialidade_profissional')->insert([
            ['profissional_id' => 1, 'especialidade_id' => 1],
            ['profissional_id' => 1, 'especialidade_id' => 2],
        ]);


        DB::table('users')->insert([
            [
                'name' => 'Admin',
                'email' => 'admin@anb.com',
                'profissional_id' => 1,
                'password' => bcrypt('12345678'),
                'imagem' => 'LOGO_01_VERDE.png',
                'permisao_id' => 1,
            ],
            [
                'name' => 'Medico',
                'email' => 'medico@anb.com',
                'profissional_id' => 1,
                'password' => bcrypt('12345678'),
                'imagem' => 'LOGO_01_VERDE.png',
                'permisao_id' => 1,
            ],
            [
                'name' => 'Recepcao',
                'email' => 'recepcao@anb.com',
                'profissional_id' => 2,
                'password' => bcrypt('12345678'),
                'imagem' => 'LOGO_01_VERDE.png',
                'permisao_id' => 2,
            ],
        ]);

        DB::table('permissao_user')->insert([
            ['user_id' => 1, 'permisao_id' => 3],
            ['user_id' => 2, 'permisao_id' => 1],
            ['user_id' => 3, 'permisao_id' => 2],
        ]);

        DB::table('pacientes')->insert([
            [
                'name' => 'Ednaldo Santos de Jesus',
                'sobrenome' => 'Souza',
                'email' => $faker->email,
                'nasc' => $faker->date($format = 'Y-m-d', $max = 'now'),
                'cpf' => '123.123.123-12', // CPF sem pontuação
                'cep' => $faker->postcode,
                'rua' => $faker->streetAddress,
                'bairro' => $faker->streetName,
                'cidade' => $faker->city,
                'uf' => $faker->stateAbbr,
                'numero' => '2',
                'complemento' => $faker->secondaryAddress,
                'telefone' => $faker->phoneNumber,
                'celular' => '(71) 98608-2537',
                'nome_social' => null,
                'nome_pai' => $faker->firstNameMale . ' ' . $faker->lastName,
                'nome_mae' => $faker->firstNameFemale . ' ' . $faker->lastName,
                'acompanhante' => null,
                'genero' => 'M',
                'rg' => '53.335.333-3', // RG sem pontuação
                'certidao' => null,
                'pcd' => 'N',
                'estado_civil' => 'Solteiro(a)',
                'sus' => $faker->numerify('###.####.####'),
                'convenio_id' => 2, // Convenio 'Particular'
                'matricula' => $faker->numerify('###'),
                'plano' => 'Basic',
                'titular' => null,
                'produto' => null,
                'cor' => 'Branco',
                'imagem' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'validade' => $faker->date($format = 'Y-m-d', $max = 'now')
            ],
            [
                'name' => 'Fabricio Souza de Oliveira',
                'sobrenome' => 'Tavares',
                'email' => $faker->email,
                'nasc' => $faker->date($format = 'Y-m-d', $max = 'now'),
                'cpf' => '123.123.123-12', // CPF sem pontuação
                'cep' => $faker->postcode,
                'rua' => $faker->streetAddress,
                'bairro' => $faker->streetName,
                'cidade' => $faker->city,
                'uf' => $faker->stateAbbr,
                'numero' => '2',
                'complemento' => $faker->secondaryAddress,
                'telefone' => $faker->phoneNumber,
                'celular' => '(71) 98608-2537',
                'nome_social' => null,
                'nome_pai' => $faker->firstNameMale . ' ' . $faker->lastName,
                'nome_mae' => $faker->firstNameFemale . ' ' . $faker->lastName,
                'acompanhante' => null,
                'genero' => 'M',
                'rg' => '53.335.333-3', // RG sem pontuação
                'certidao' => null,
                'pcd' => 'N',
                'estado_civil' => 'Solteiro(a)',
                'sus' => $faker->numerify('###.####.####'),
                'convenio_id' => 2, // Convenio 'Amil'
                'matricula' => $faker->numerify('###'),
                'plano' => 'Gold',
                'titular' => null,
                'produto' => null,
                'cor' => 'Branco',
                'imagem' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'validade' => $faker->date($format = 'Y-m-d', $max = 'now')
            ]
        ]);

        DB::table('empresas')->insert([
            [
                'name' => 'Eprontuario',
                'email' => $faker->email,
                'cnpj' => $faker->numerify('##.###.###/####-##'), // Gerando CNPJ aleatório
                'cep' => $faker->postcode,
                'rua' => $faker->streetAddress,
                'bairro' => $faker->streetName,
                'cidade' => $faker->city,
                'uf' => $faker->stateAbbr,
                'numero' => '2',
                'complemento' => $faker->secondaryAddress,
                'celular' => '(71) 98608-2537',
                'telefone' => $faker->phoneNumber,
                'crm' => $faker->numerify('######'), // CRM aleatório
                'fantasia' => 'Nome Fantasia',
                'medico' => $faker->name('male'),
                'imagem' => 'LOGO_01_VERDE.png', // Mantendo a logo fixa
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'licenca' => '2030-01-01',
                'contrato' => null, // Se não houver valor para contrato, definir como null
                'cnes' => $faker->numerify('###') // CNES aleatório
            ]
        ]);

        DB::table('feriados')->insert([
            [
                'data' => '2024-01-01',
                'feriado' => 'Ano Novo'
            ],
            [
                'data' => '2024-04-21',
                'feriado' => 'Tiradentes'
            ],
            [
                'data' => '2024-05-01',
                'feriado' => 'Dia do Trabalho'
            ],
            [
                'data' => '2024-09-07',
                'feriado' => 'Independência do Brasil'
            ],
            [
                'data' => '2024-10-12',
                'feriado' => 'Nossa Senhora Aparecida'
            ],
            [
                'data' => '2024-11-02',
                'feriado' => 'Finados'
            ],
            [
                'data' => '2024-11-15',
                'feriado' => 'Proclamação da República'
            ],
            [
                'data' => '2024-12-25',
                'feriado' => 'Natal'
            ],
        ]);

        DB::table('produtos')->insert([
            [
                'nome' => 'Luvas Cirúrgicas',
                'marca' => 'MedLine',
                'tipo' => 'MATERIAL',
                'grupo' => 'EPI',
                'sub_grupo' => 'Luvas',
                'preco_venda' => 12.50,
                'natureza' => 'Descartável',
                'ativo' => 'SIM',
                'controlado' => 'NÃO',
                'padrao' => 'SIM',
                'ccih' => 'SIM',
                'generico' => 'NÃO',
                'consignado' => 'SIM',
                'disp_emergencia' => 'SIM',
                'disp_paciente' => 'NÃO',
                'fracionado' => 'NÃO',
                'imobilizado' => 'NÃO',
            ],
            [
                'nome' => 'Máscaras N95',
                'marca' => '3M',
                'tipo' => 'MATERIAL',
                'grupo' => 'EPI',
                'sub_grupo' => 'Máscaras',
                'preco_venda' => 35.00,
                'natureza' => 'Descartável',
                'ativo' => 'SIM',
                'controlado' => 'NÃO',
                'padrao' => 'SIM',
                'ccih' => 'SIM',
                'generico' => 'NÃO',
                'consignado' => 'SIM',
                'disp_emergencia' => 'SIM',
                'disp_paciente' => 'NÃO',
                'fracionado' => 'NÃO',
                'imobilizado' => 'NÃO',
            ],
        ]);

        DB::table('tipo_atendimentos')->insert([
            [
                'atendimento' => 'Primeira Consulta',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'atendimento' => 'Retorno',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'atendimento' => 'Pré-natal',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'atendimento' => 'Por Encaminhamento',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

        DB::table('medicamentos')->insert([
            ['nome' => 'abatacepte'],
            ['nome' => 'acetazolamida'],
            ['nome' => 'ácido nicotínico'],
            ['nome' => 'ácido ursodesoxicólico'],
            ['nome' => 'ácido zoledrônico'],
            ['nome' => 'acitretina'],
            ['nome' => 'adalimumabe'],
            ['nome' => 'alentuzumabe'],
            ['nome' => 'alfaglicosidase'],
            ['nome' => 'alfadornase'],
            ['nome' => 'alfaelosulfase'],
            ['nome' => 'alfaepoetina'],
            ['nome' => 'alfainterferona 2b'],
            ['nome' => 'alfavelaglicerase'],
            ['nome' => 'alfavestronidase'],
            ['nome' => 'amantadina'],
            ['nome' => 'ambrisentana'],
            ['nome' => 'atorvastatina'],
            ['nome' => 'azatioprina'],
            ['nome' => 'baricitinibe'],
            ['nome' => 'betainterferona'],
            ['nome' => 'bezafibrato'],
            ['nome' => 'bimatoprosta'],
            ['nome' => 'biotina'],
            ['nome' => 'bosentana'],
            ['nome' => 'brimonidina'],
            ['nome' => 'brinzolamida'],
            ['nome' => 'budesonida'],
            ['nome' => 'burosumabe'],
            ['nome' => 'cabergolina'],
            ['nome' => 'calcipotriol'],
            ['nome' => 'calcitonina'],
            ['nome' => 'calcitriol'],
            ['nome' => 'certolizumabe pegol'],
            ['nome' => 'ciclofosfamida'],
            ['nome' => 'ciclosporina'],
            ['nome' => 'cinacalcete'],
            ['nome' => 'ciprofibrato'],
            ['nome' => 'ciproterona'],
            ['nome' => 'clobazam'],
            ['nome' => 'clobetasol'],
            ['nome' => 'clopidogrel'],
            ['nome' => 'cloroquina'],
            ['nome' => 'clozapina'],
            ['nome' => 'codeína'],
            ['nome' => 'danazol'],
            ['nome' => 'dapagliflozina'],
            ['nome' => 'deferasirox'],
            ['nome' => 'deferiprona'],
            ['nome' => 'desferroxamina'],
            ['nome' => 'desmopressina'],
            ['nome' => 'donepezila'],
            ['nome' => 'dorzolamida'],
            ['nome' => 'eculizumabe'],
            ['nome' => 'eltrombopague olamina'],
            ['nome' => 'enoxaparina sódica'],
            ['nome' => 'entacapona'],
            ['nome' => 'etanercepte'],
            ['nome' => 'etossuximida'],
            ['nome' => 'everolimo'],
            ['nome' => 'fenofibrato'],
            ['nome' => 'fenoterol'],
            ['nome' => 'filgrastim'],
            ['nome' => 'fingolimode'],
            ['nome' => 'fludrocortisona'],
            ['nome' => 'formoterol'],
            ['nome' => 'formoterol + budesonida'],
            ['nome' => 'fumarato de dimetila'],
            ['nome' => 'gabapentina'],
            ['nome' => 'galantamina'],
            ['nome' => 'galsulfase'],
            ['nome' => 'genfibrozila'],
            ['nome' => 'glatiramer'],
            ['nome' => 'golimumabe'],
            ['nome' => 'gosserrelina'],
            ['nome' => 'hidroxicloroquina'],
            ['nome' => 'hidroxiuréia'],
            ['nome' => 'idursulfase alfa'],
            ['nome' => 'iloprosta'],
            ['nome' => 'imiglucerase'],
            ['nome' => 'imunoglobulina humana'],
            ['nome' => 'infliximabe'],
            ['nome' => 'Insulina Asparte'],
            ['nome' => 'isotretinoína'],
            ['nome' => 'Ivacaftor'],
            ['nome' => 'Ivacaftor / Elexacaftor / Tezacaftor + Ivacaftor'],
            ['nome' => 'lamotrigina'],
            ['nome' => 'lanreotida'],
            ['nome' => 'laronidase'],
            ['nome' => 'latanoprosta'],
            ['nome' => 'leflunomida'],
            ['nome' => 'leuprorrelina'],
            ['nome' => 'levetiracetam'],
            ['nome' => 'memantina'],
            ['nome' => 'mesalazina'],
            ['nome' => 'mepolizumabe'],
            ['nome' => 'metadona'],
            ['nome' => 'metilprednisolona'],
            ['nome' => 'metotrexato'],
            ['nome' => 'micofenolato de mofetila'],
            ['nome' => 'micofenolato de sódio'],
            ['nome' => 'miglustate'],
            ['nome' => 'morfina'],
            ['nome' => 'naproxeno'],
            ['nome' => 'natalizumabe'],
            ['nome' => 'nusinersena'],
            ['nome' => 'octreotida'],
            ['nome' => 'olanzapina'],
            ['nome' => 'omalizumabe'],
            ['nome' => 'pamidronato'],
            ['nome' => 'pancreatina'],
            ['nome' => 'paricalcitol'],
            ['nome' => 'penicilamina'],
            ['nome' => 'pilocarpina'],
            ['nome' => 'piridostigmina'],
            ['nome' => 'pramipexol'],
            ['nome' => 'pravastatina'],
            ['nome' => 'primidona'],
            ['nome' => 'quetiapina'],
            ['nome' => 'raloxifeno'],
            ['nome' => 'rasagilina'],
            ['nome' => 'risanquizumabe'],
            ['nome' => 'riluzol'],
            ['nome' => 'risdiplam'],
            ['nome' => 'risedronato'],
            ['nome' => 'risperidona'],
            ['nome' => 'rituximabe'],
            ['nome' => 'rivastigmina'],
            ['nome' => 'romosozumabe'],
            ['nome' => 'sacarato de hidróxido férrico'],
            ['nome' => 'sacubitril valsartana sódica hidratada'],
            ['nome' => 'sapropterina'],
            ['nome' => 'secuquinumabe'],
            ['nome' => 'selegilina'],
            ['nome' => 'selexipague'],
            ['nome' => 'sevelamer'],
            ['nome' => 'sildenafila'],
            ['nome' => 'sirolimo'],
            ['nome' => 'somatropina'],
            ['nome' => 'sulfassalazina'],
            ['nome' => 'tafamidis'],
            ['nome' => 'tacrolimo'],
            ['nome' => 'taliglucerase alfa'],
            ['nome' => 'teriflunomida'],
            ['nome' => 'timolol'],
            ['nome' => 'tiotrópio + olodaterol'],
            ['nome' => 'tobramicina'],
            ['nome' => 'tocilizumabe'],
            ['nome' => 'tofacitinibe'],
            ['nome' => 'topiramato'],
            ['nome' => 'toxina botulínica tipo a'],
            ['nome' => 'travoprosta'],
            ['nome' => 'trientina'],
            ['nome' => 'triexifenidil'],
            ['nome' => 'triptorrelina'],
            ['nome' => 'umeclidínio + vilanterol'],
            ['nome' => 'upadacitinibe'],
            ['nome' => 'ustequinumabe'],
            ['nome' => 'vedolizumabe'],
            ['nome' => 'vigabatrina'],
            ['nome' => 'ziprasidona'],
            ['nome' => 'complemento alimentar']
        ]);

        DB::table('procedimentos')->insert([
            ['codigo' => '0000000000', 'procedimento' => 'RETORNO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202090027', 'procedimento' => 'ADENOGRAMA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202080056', 'procedimento' => 'BACILOSCOPIA DIRETA P/ BAAR (HANSENIASE)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202080064', 'procedimento' => 'BACILOSCOPIA DIRETA P/ BAAR TUBERCULOS (CONTROLE)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202080048', 'procedimento' => 'BACILOSCOPIA DIRETA P/ BAAR TUBERCULOSE (DIAGNÓSTICA)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020010', 'procedimento' => 'CITOQUIMICA HEMATOLOGICA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050033', 'procedimento' => 'CLEARANCE DE FOSFATO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050041', 'procedimento' => 'CLEARANCE DE UREIA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030016', 'procedimento' => 'CONTAGEM DE LINFOCITOS B', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030024', 'procedimento' => 'CONTAGEM DE LINFOCITOS CD4/CD8', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030032', 'procedimento' => 'CONTAGEM DE LINFOCITOS T TOTAIS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202090051', 'procedimento' => 'CONTAGEM ESPECIFICA DE CELULAS NO LIQUOR', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202090060', 'procedimento' => 'CONTAGEM GLOBAL DE CELULAS NO LIQUOR', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202080099', 'procedimento' => 'CULTURA DO LEITE HUMANO (POS-PASTEURIZAÇÃO)', 'idade' => '10 ANOS - 49 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202080110', 'procedimento' => 'CULTURA PARA BAAR', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202080129', 'procedimento' => 'CULTURA PARA BACTERIAS ANAEROBICAS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202031250', 'procedimento' => 'DETECÇÃO DE RNA DO HTLV-1', 'idade' => '19 ANOS - 130 ANOS', 'limite' => '1'],
            ['codigo' => '0202120015', 'procedimento' => 'DETERMINACAO DE ANTICORPOS ANTIPLAQUETARIOS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010023', 'procedimento' => 'DETERMINACAO DE CAPACIDADE DE FIXACAO DO FERRO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202100014', 'procedimento' => 'DETERMINACAO DE CARIOTIPO EM CULTURA DE LONGA DURACAO (C/ TECNICA DE BANDAS)', 'idade' => '0 MESES - 130 ANOS', 'limite' => '1'],
            ['codigo' => '0202100030', 'procedimento' => 'DETERMINACAO DE CARIOTIPO EM SANGUE PERIFERICO (C/TECNICA DE BANDAS)', 'idade' => '0 MESES - 130 ANOS', 'limite' => '1'],
            ['codigo' => '0202030067', 'procedimento' => 'DETERMINACAO DE COMPLEMENTO (CH50)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020045', 'procedimento' => 'DETERMINACAO DE CURVA DE RESISTENCIA GLOBULAR', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010040', 'procedimento' => 'DETERMINACAO DE CURVA GLICEMICA (2 DOSAGENS)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020053', 'procedimento' => 'DETERMINACAO DE ENZIMAS ERITROCITARIAS (CADA)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030075', 'procedimento' => 'DETERMINACAO DE FATOR REUMATOIDE', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050068', 'procedimento' => 'DETERMINACAO DE OSMOLALIDADE', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010082', 'procedimento' => 'DETERMINACAO DE OSMOLARIDADE', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060020', 'procedimento' => 'DETERMINACAO DE RETENCAO DE T3', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020061', 'procedimento' => 'DETERMINACAO DE SULFO-HEMOGLOBINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060039', 'procedimento' => 'DETERMINACAO DE T3 REVERSO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020088', 'procedimento' => 'DETERMINACAO DE TEMPO DE LISE DA EUGLOBULINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020100', 'procedimento' => 'DETERMINACAO DE TEMPO DE SANGRAMENTO DE IVY', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020118', 'procedimento' => 'DETERMINACAO DE TEMPO DE SOBREVIDA DE HEMACIAS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202120023', 'procedimento' => 'DETERMINACAO DIRETA E REVERSA DE GRUPO ABO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030083', 'procedimento' => 'DETERMINACAO QUANTITATIVA DE PROTEINA C REATIVA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202110109', 'procedimento' => 'DOSAGEM DA ATIVIDADE DA BIOTINIDASE EM AMOSTRAS DE SANGUE EM PAPEL DE FILTRO', 'idade' => '0 MESES - 1 MÊS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202110095', 'procedimento' => 'DOSAGEM DE 17 HIDROXI PROGESTERONA EM PAPEL DE FILTRO (COMPONENTE DO TESTE DO PEZINHO)', 'idade' => '0 MESES - 1 MÊS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060047', 'procedimento' => 'DOSAGEM DE 17-ALFA-HIDROXIPROGESTERONA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060055', 'procedimento' => 'DOSAGEM DE 17-CETOSTEROIDES TOTAIS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060063', 'procedimento' => 'DOSAGEM DE 17-HIDROXICORTICOSTEROIDES', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010767', 'procedimento' => 'DOSAGEM DE 25 HIDROXIVITAMINA D', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010090', 'procedimento' => 'DOSAGEM DE 5-NUCLEOTIDASE', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010104', 'procedimento' => 'DOSAGEM DE ACETONA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060071', 'procedimento' => 'DOSAGEM DE ACIDO 5-HIDROXI-INDOL-ACETICO (SEROTONINA)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010112', 'procedimento' => 'DOSAGEM DE ACIDO ASCORBICO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070018', 'procedimento' => 'DOSAGEM DE ACIDO DELTA-AMINOLEVULINICO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070026', 'procedimento' => 'DOSAGEM DE ACIDO HIPURICO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070034', 'procedimento' => 'DOSAGEM DE ACIDO MANDELICO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070042', 'procedimento' => 'DOSAGEM DE ACIDO METIL-HIPURICO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070050', 'procedimento' => 'DOSAGEM DE ACIDO VALPROICO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010139', 'procedimento' => 'DOSAGEM DE ACIDO VANILMANDELICO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060080', 'procedimento' => 'DOSAGEM DE ADRENOCORTICOTROFICO (ACTH)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070077', 'procedimento' => 'DOSAGEM DE ALCOOL ETILICO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010147', 'procedimento' => 'DOSAGEM DE ALDOLASE', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060098', 'procedimento' => 'DOSAGEM DE ALDOSTERONA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010155', 'procedimento' => 'DOSAGEM DE ALFA-1-ANTITRIPSINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010163', 'procedimento' => 'DOSAGEM DE ALFA-1-GLICOPROTEINA ACIDA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010171', 'procedimento' => 'DOSAGEM DE ALFA-2-MACROGLOBULINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030091', 'procedimento' => 'DOSAGEM DE ALFA-FETOPROTEINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070085', 'procedimento' => 'DOSAGEM DE ALUMINIO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060101', 'procedimento' => 'DOSAGEM DE AMP CICLICO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060110', 'procedimento' => 'DOSAGEM DE ANDROSTENEDIONA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070107', 'procedimento' => 'DOSAGEM DE ANFETAMINAS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202031187', 'procedimento' => 'DOSAGEM DE ANTICORPOS ANTITRANSGLUTAMINAISE RECOMBINANTE HUMANO IGA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020177', 'procedimento' => 'DOSAGEM DE ANTITROMBINA III', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030113', 'procedimento' => 'DOSAGEM DE BETA-2-MICROGLOBULINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060128', 'procedimento' => 'DOSAGEM DE CALCITONINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070166', 'procedimento' => 'DOSAGEM DE CARBOXI-HEMOGLOBINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010236', 'procedimento' => 'DOSAGEM DE CAROTENO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010252', 'procedimento' => 'DOSAGEM DE CERULOPLASMINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070174', 'procedimento' => 'DOSAGEM DE CHUMBO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070182', 'procedimento' => 'DOSAGEM DE CICLOSPORINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050084', 'procedimento' => 'DOSAGEM DE CITRATO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070190', 'procedimento' => 'DOSAGEM DE COBRE', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010309', 'procedimento' => 'DOSAGEM DE COLINESTERASE', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060136', 'procedimento' => 'DOSAGEM DE CORTISOL', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010333', 'procedimento' => 'DOSAGEM DE CREATINOFOSFOQUINASE FRACAO MB', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030148', 'procedimento' => 'DOSAGEM DE CRIOAGLUTININA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060144', 'procedimento' => 'DOSAGEM DE DEHIDROEPIANDROSTERONA (DHEA)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010341', 'procedimento' => 'DOSAGEM DE DESIDROGENASE ALFA-HIDROXIBUTIRICA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070204', 'procedimento' => 'DOSAGEM DE DIGITALICOS (DIGOXINA, DIGITOXINA)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060152', 'procedimento' => 'DOSAGEM DE DIHIDROTESTOTERONA (DHT)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202040011', 'procedimento' => 'DOSAGEM DE ESTERCOBILINOGENIO FECAL', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060160', 'procedimento' => 'DOSAGEM DE ESTRADIOL', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060179', 'procedimento' => 'DOSAGEM DE ESTRIOL', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060187', 'procedimento' => 'DOSAGEM DE ESTRONA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070212', 'procedimento' => 'DOSAGEM DE ETOSSUXIMIDA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020185', 'procedimento' => 'DOSAGEM DE FATOR II', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020193', 'procedimento' => 'DOSAGEM DE FATOR IX', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020207', 'procedimento' => 'DOSAGEM DE FATOR V', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020215', 'procedimento' => 'DOSAGEM DE FATOR VII', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020223', 'procedimento' => 'DOSAGEM DE FATOR VIII', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020231', 'procedimento' => 'DOSAGEM DE FATOR VIII (INIBIDOR)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020258', 'procedimento' => 'DOSAGEM DE FATOR X', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020266', 'procedimento' => 'DOSAGEM DE FATOR XI', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020282', 'procedimento' => 'DOSAGEM DE FATOR XIII', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202110044', 'procedimento' => 'DOSAGEM DE FENILALANINA (CONTROLE /DIAGNOSTICO TARDIO)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202110060', 'procedimento' => 'DOSAGEM DE FENILALANINA TSH OU T4 E DETECCAO DA VARIANTE DE HEMOGLOBINA (COMPONENTE DO TESTE DO PEZINHO)', 'idade' => '0 MESES - 1 MÊS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070220', 'procedimento' => 'DOSAGEM DE FENITOINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070239', 'procedimento' => 'DOSAGEM DE FENOL', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020290', 'procedimento' => 'DOSAGEM DE FIBRINOGENIO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010406', 'procedimento' => 'DOSAGEM DE FOLATO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070247', 'procedimento' => 'DOSAGEM DE FORMALDEIDO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010414', 'procedimento' => 'DOSAGEM DE FOSFATASE ACIDA TOTAL', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010430', 'procedimento' => 'DOSAGEM DE FOSFORO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010449', 'procedimento' => 'DOSAGEM DE FRACAO PROSTATICA DA FOSFATASE ACIDA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202090108', 'procedimento' => 'DOSAGEM DE FRUTOSE', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202090116', 'procedimento' => 'DOSAGEM DE FRUTOSE NO ESPERMA', 'idade' => '10 ANOS - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010457', 'procedimento' => 'DOSAGEM DE GALACTOSE', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060195', 'procedimento' => 'DOSAGEM DE GASTRINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010481', 'procedimento' => 'DOSAGEM DE GLICOSE-6-FOSFATO DESIDROGENASE', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060209', 'procedimento' => 'DOSAGEM DE GLOBULINA TRANSPORTADORA DE TIROXINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202040020', 'procedimento' => 'DOSAGEM DE GORDURA FECAL', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010490', 'procedimento' => 'DOSAGEM DE HAPTOGLOBINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020304', 'procedimento' => 'DOSAGEM DE HEMOGLOBINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020312', 'procedimento' => 'DOSAGEM DE HEMOGLOBINA - INSTABILIDADE A 37OC', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020320', 'procedimento' => 'DOSAGEM DE HEMOGLOBINA FETAL', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010503', 'procedimento' => 'DOSAGEM DE HEMOGLOBINA GLICOSILADA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010511', 'procedimento' => 'DOSAGEM DE HIDROXIPROLINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060225', 'procedimento' => 'DOSAGEM DE HORMONIO DE CRESCIMENTO (HGH)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060233', 'procedimento' => 'DOSAGEM DE HORMONIO FOLICULO-ESTIMULANTE (FSH)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060241', 'procedimento' => 'DOSAGEM DE HORMONIO LUTEINIZANTE (LH)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030156', 'procedimento' => 'DOSAGEM DE IMUNOGLOBULINA A (IGA)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030164', 'procedimento' => 'DOSAGEM DE IMUNOGLOBULINA E (IGE)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030180', 'procedimento' => 'DOSAGEM DE IMUNOGLOBULINA M (IGM)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030199', 'procedimento' => 'DOSAGEM DE INIBIDOR DE C1-ESTERASE', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010520', 'procedimento' => 'DOSAGEM DE ISOMERASE-FOSFOHEXOSE', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010546', 'procedimento' => 'DOSAGEM DE LEUCINO-AMINOPEPTIDASE', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010554', 'procedimento' => 'DOSAGEM DE LIPASE', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070263', 'procedimento' => 'DOSAGEM DE MERCURIO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070271', 'procedimento' => 'DOSAGEM DE META-HEMOGLOBINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050092', 'procedimento' => 'DOSAGEM DE MICROALBUMINA NA URINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010570', 'procedimento' => 'DOSAGEM DE MUCO-PROTEINAS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050106', 'procedimento' => 'DOSAGEM DE OXALATO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060276', 'procedimento' => 'DOSAGEM DE PARATORMONIO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060284', 'procedimento' => 'DOSAGEM DE PEPTIDEO C', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010589', 'procedimento' => 'DOSAGEM DE PIRUVATO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010597', 'procedimento' => 'DOSAGEM DE PORFIRINAS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060292', 'procedimento' => 'DOSAGEM DE PROGESTERONA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060306', 'procedimento' => 'DOSAGEM DE PROLACTINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050114', 'procedimento' => 'DOSAGEM DE PROTEINAS (URINA DE 24 HORAS)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060314', 'procedimento' => 'DOSAGEM DE RENINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070310', 'procedimento' => 'DOSAGEM DE SALICILATOS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060322', 'procedimento' => 'DOSAGEM DE SOMATOMEDINA C (IGF1)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060330', 'procedimento' => 'DOSAGEM DE SULFATO DE HIDROEPIANDROSTERONA (DHEAS)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070328', 'procedimento' => 'DOSAGEM DE SULFATOS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070336', 'procedimento' => 'DOSAGEM DE TEOFILINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060349', 'procedimento' => 'DOSAGEM DE TESTOSTERONA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060357', 'procedimento' => 'DOSAGEM DE TESTOSTERONA LIVRE', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070344', 'procedimento' => 'DOSAGEM DE TIOCIANATO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060365', 'procedimento' => 'DOSAGEM DE TIREOGLOBULINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010660', 'procedimento' => 'DOSAGEM DE TRANSFERRINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202110079', 'procedimento' => 'DOSAGEM DE TRIPSINA IMUNORREATIVA (COMPONENTE DO TESTE DO PEZINHO)', 'idade' => '0 MESES - 1 MÊS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202110087', 'procedimento' => 'DOSAGEM DE TSH E T4 LIVRE (CONTROLE /DIAGNOSTICO TARDIO)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010708', 'procedimento' => 'DOSAGEM DE VITAMINA B12', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070352', 'procedimento' => 'DOSAGEM DE ZINCO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202031217', 'procedimento' => 'DOSAGEM DO ANTÍGENO CA 125', 'idade' => '19 ANOS - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050122', 'procedimento' => 'DOSAGEM E/OU FRACIONAMENTO DE ACIDOS ORGANICOS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020355', 'procedimento' => 'ELETROFORESE DE HEMOGLOBINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010716', 'procedimento' => 'ELETROFORESE DE LIPOPROTEINAS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010724', 'procedimento' => 'ELETROFORESE DE PROTEINAS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202090159', 'procedimento' => 'ELETROFORESE DE PROTEINAS C/ CONCENTRACAO NO LIQUOR', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020363', 'procedimento' => 'ERITROGRAMA (ERITROCITOS, HEMOGLOBINA, HEMATOCRITO)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202090175', 'procedimento' => 'ESPLENOGRAMA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202040038', 'procedimento' => 'EXAME COPROLOGICO FUNCIONAL', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050130', 'procedimento' => 'EXAME QUALITATIVO DE CALCULOS URINARIOS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202120031', 'procedimento' => 'FENOTIPAGEM DE SISTEMA RH - HR', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010732', 'procedimento' => 'GASOMETRIA (PH PCO2 PO2 BICARBONATO AS2 (EXCESSO OU DEFICIT BASE)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020371', 'procedimento' => 'HEMATOCRITO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202080153', 'procedimento' => 'HEMOCULTURA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202080161', 'procedimento' => 'IDENTIFICACAO AUTOMATIZADA DE MICROORGANISMOS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202040046', 'procedimento' => 'IDENTIFICACAO DE FRAGMENTOS DE HELMINTOS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030229', 'procedimento' => 'IMUNOELETROFORESE DE PROTEINAS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020398', 'procedimento' => 'LEUCOGRAMA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202090191', 'procedimento' => 'MIELOGRAMA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202080170', 'procedimento' => 'PEQUISA DE PNEUMOCYSTI CARINI', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050149', 'procedimento' => 'PESQUISA / DOSAGEM DE AMINOACIDOS (POR CROMATOGRAFIA)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030253', 'procedimento' => 'PESQUISA DE ANTICORPO IGG ANTICARDIOLIPINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030261', 'procedimento' => 'PESQUISA DE ANTICORPO IGM ANTICARDIOLIPINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030270', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTI-DNA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030288', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTI-HELICOBACTER PYLORI', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030296', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTI-HIV-1 (WESTERN BLOT)', 'idade' => '2 ANOS - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030300', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTI-HIV-1 + HIV-2 (ELISA)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030318', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTI-HTLV-1 + HTLV-2', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030326', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTI-RIBONUCLEOPROTEINA (RNP)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030334', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTI-SCHISTOSOMAS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030342', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTI-SM', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030350', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTI-SS-A (RO)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030369', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTI-SS-B (LA)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030377', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTIADENOVIRUS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030393', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTIASPERGILLUS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030415', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTICISTICERCO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030423', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTICLAMIDIA (POR IMUNOFLUORESCENCIA)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202031268', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTICORPOS ANTI-HTLV-1 (WESTERN-BLOT)', 'idade' => '19 ANOS - 130 ANOS', 'limite' => '1'],
            ['codigo' => '0202030431', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTICORTEX SUPRARENAL', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030440', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTIEQUINOCOCOS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030458', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTIESCLERODERMA (SCL 70)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030482', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTIFIGADO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030504', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTIGLOMERULO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030512', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTIILHOTA DE LANGERHANS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030520', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTIINSULINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030539', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTILEPTOSPIRAS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030547', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTILISTERIA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030555', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTIMICROSSOMAS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030571', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTIMUSCULO ESTRIADO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030601', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTIPARIETAIS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030628', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTITIREOGLOBULINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030644', 'procedimento' => 'PESQUISA DE ANTICORPOS CONTRA ANTIGENO E DO VIRUS DA HEPATITE B (ANTI-HBE)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030695', 'procedimento' => 'PESQUISA DE ANTICORPOS CONTRA O VIRUS DO SARAMPO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030709', 'procedimento' => 'PESQUISA DE ANTICORPOS CONTRA PARACOCCIDIOIDES BRASILIENSIS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030725', 'procedimento' => 'PESQUISA DE ANTICORPOS EIE ANTICLAMIDIA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030733', 'procedimento' => 'PESQUISA DE ANTICORPOS HETEROFILOS CONTA O VIRUS EPSTEIN-BARR', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030741', 'procedimento' => 'PESQUISA DE ANTICORPOS IGG ANTICITOMEGALOVIRUS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030806', 'procedimento' => 'PESQUISA DE ANTICORPOS IGG CONTRA O VIRUS DA HEPATITE A (HAV-IGG)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030822', 'procedimento' => 'PESQUISA DE ANTICORPOS IGG CONTRA O VIRUS DA VARICELA-HERPES ZOSTER', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030849', 'procedimento' => 'PESQUISA DE ANTICORPOS IGG CONTRA O VIRUS HERPES SIMPLES', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030784', 'procedimento' => 'PESQUISA DE ANTICORPOS IGG E IGM CONTRA ANTIGENO CENTRAL DO VIRUS DA HEPATITE B (ANTI-HBC-TOTAL)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030857', 'procedimento' => 'PESQUISA DE ANTICORPOS IGM ANTICITOMEGALOVIRUS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030865', 'procedimento' => 'PESQUISA DE ANTICORPOS IGM ANTILEISHMANIAS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030890', 'procedimento' => 'PESQUISA DE ANTICORPOS IGM CONTRA ANTIGENO CENTRAL DO VIRUS DA HEPATITE B (ANTI-HBC-IGM)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030938', 'procedimento' => 'PESQUISA DE ANTICORPOS IGM CONTRA O VIRUS DA VARICELA-HERPES ZOSTER', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030954', 'procedimento' => 'PESQUISA DE ANTICORPOS IGM CONTRA O VIRUS HERPES SIMPLES', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202120058', 'procedimento' => 'PESQUISA DE ANTICORPOS IRREGULARES PELO METODO DA ELUICAO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030962', 'procedimento' => 'PESQUISA DE ANTIGENO CARCINOEMBRIONARIO (CEA)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030989', 'procedimento' => 'PESQUISA DE ANTIGENO E DO VIRUS DA HEPATITE B (HBEAG)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202090230', 'procedimento' => 'PESQUISA DE CARACTERES FISICOS NO LIQUOR', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050190', 'procedimento' => 'PESQUISA DE CISTINA NA URINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050203', 'procedimento' => 'PESQUISA DE COPROPORFIRINA NA URINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202031004', 'procedimento' => 'PESQUISA DE CRIOGLOBULINAS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202040054', 'procedimento' => 'PESQUISA DE ENTEROBIUS VERMICULARES (OXIURUS OXIURA)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050211', 'procedimento' => 'PESQUISA DE ERROS INATOS DO METABOLISMO NA URINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202090264', 'procedimento' => 'PESQUISA DE ESPERMATOZOIDES (APOS VASECTOMIA)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202080196', 'procedimento' => 'PESQUISA DE ESTREPTOCOCOS BETA-HEMOLITICOS DO GRUPO A', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020436', 'procedimento' => 'PESQUISA DE FILARIA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050238', 'procedimento' => 'PESQUISA DE FRUTOSE NA URINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050246', 'procedimento' => 'PESQUISA DE GALACTOSE NA URINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202040070', 'procedimento' => 'PESQUISA DE GORDURA FECAL', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202080218', 'procedimento' => 'PESQUISA DE HELICOBACTER PYLORI', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202031020', 'procedimento' => 'PESQUISA DE HIV-1 POR IMUNOFLUORESCENCIA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050262', 'procedimento' => 'PESQUISA DE HOMOCISTINA NA URINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202031039', 'procedimento' => 'PESQUISA DE IMUNOGLOBULINA E (IGE) ALERGENO-ESPECIFICA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202040089', 'procedimento' => 'PESQUISA DE LARVAS NAS FEZES', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202080226', 'procedimento' => 'PESQUISA DE LEPTOSPIRAS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202040100', 'procedimento' => 'PESQUISA DE LEVEDURAS NAS FEZES', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060470', 'procedimento' => 'PESQUISA DE MACROPROLACTINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202040119', 'procedimento' => 'PESQUISA DE OVOS DE SCHISTOSOMAS (EM FRAGMENTO DE MUCOSA)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020452', 'procedimento' => 'PESQUISA DE PLASMODIOS POR GOTA ESPESSA E ESFREGAÇO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050297', 'procedimento' => 'PESQUISA DE PORFOBILINOGENIO NA URINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050300', 'procedimento' => 'PESQUISA DE PROTEINAS URINARIAS (POR ELETROFORESE)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202040143', 'procedimento' => 'PESQUISA DE SANGUE OCULTO NAS FEZES', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202040151', 'procedimento' => 'PESQUISA DE SUBSTANCIAS REDUTORAS NAS FEZES', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050319', 'procedimento' => 'PESQUISA DE TIROSINA NA URINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020460', 'procedimento' => 'PESQUISA DE TRIPANOSSOMA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202040160', 'procedimento' => 'PESQUISA DE TRIPSINA NAS FEZES', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202080242', 'procedimento' => 'PROVA CONFIRMATÓRIA DA PRESENÇA DE MICRO-ORGANISMOS COLIFORMES', 'idade' => 'NÃO SE APLICA', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010740', 'procedimento' => 'PROVA DA D-XILOSE', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020487', 'procedimento' => 'PROVA DE CONSUMO DE PROTROMBINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050327', 'procedimento' => 'PROVA DE DILUICAO (URINA)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202090302', 'procedimento' => 'PROVA DO LATEX P/ PESQUISA DO FATOR REUMATOIDE', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202031071', 'procedimento' => 'QUANTIFICACAO DE RNA DO HIV-1', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020517', 'procedimento' => 'RASTREIO P/ DEFICIENCIA DE ENZIMAS ERITROCITARIAS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202031101', 'procedimento' => 'REACAO DE MONTENEGRO ID', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202090329', 'procedimento' => 'REACAO DE RIVALTA NO LIQUIDO SINOVIAL E DERRAMES', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020525', 'procedimento' => 'TESTE DE AGREGACAO DE PLAQUETAS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0213010577', 'procedimento' => 'TESTE DE ELISA IGG P/ IDENTIFICAÇÃO DO TOXOPLASMA GONDII (TOXOPLASMOSE)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060403', 'procedimento' => 'TESTE DE ESTIMULO DA PROLACTINA / TSH APOS TRH', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060411', 'procedimento' => 'TESTE DE ESTIMULO DA PROLACTINA APÓS CLORPROMAZINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020533', 'procedimento' => 'TESTE DE HAM (HEMOLISE ACIDA)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060446', 'procedimento' => 'TESTE DE SUPRESSAO DO CORTISOL APÓS DEXAMETASONA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010759', 'procedimento' => 'TESTE DE TOLERANCIA A INSULINA /DERRAMES ORAIS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202031110', 'procedimento' => 'TESTE NÃO TREPONEMICO P/ DETECÇÃO DE SIFILIS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202031179', 'procedimento' => 'TESTE NÃO TREPONEMICO P/ DETECÇÃO DE SIFILIS EM GESTANTES', 'idade' => '9 ANOS - 60 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202031098', 'procedimento' => 'TESTE TREPONEMICO P/ DETECÇÃO DE SIFILIS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050017', 'procedimento' => 'ANALISE DE CARACTERES FISICOS, ELEMENTOS E SEDIMENTO DA URINA (PARCIAL DE URINA)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202080013', 'procedimento' => 'ANTIBIOGRAMA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202080072', 'procedimento' => 'BACTERIOSCOPIA (GRAM)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050025', 'procedimento' => 'CLEARANCE DE CREATININA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020029', 'procedimento' => 'CONTAGEM DE PLAQUETAS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020037', 'procedimento' => 'CONTAGEM DE RETICULOCITOS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202080080', 'procedimento' => 'CULTURA DE BACTERIAS P/ IDENTIFICACAO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202080137', 'procedimento' => 'CULTURA PARA IDENTIFICACAO DE FUNGOS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010074', 'procedimento' => 'DETERMINACAO DE CURVA GLICEMICA CLASSICA (5 DOSAGENS)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020070', 'procedimento' => 'DETERMINACAO DE TEMPO DE COAGULACAO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020096', 'procedimento' => 'DETERMINACAO DE TEMPO DE SANGRAMENTO -DUKE', 'idade' => '0 MESES -130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020126', 'procedimento' => 'DETERMINACAO DE TEMPO DE TROMBINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020134', 'procedimento' => 'DETERMINACAO DE TEMPO DE TROMBOPLASTINA PARCIAL ATIVADA (TTP ATIVADA)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020142', 'procedimento' => 'DETERMINACAO DE TEMPO E ATIVIDADE DA PROTROMBINA (TAP)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020150', 'procedimento' => 'DETERMINACAO DE VELOCIDADE DE HEMOSSEDIMENTACAO (VHS)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010120', 'procedimento' => 'DOSAGEM DE ACIDO URICO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010180', 'procedimento' => 'DOSAGEM DE AMILASE', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030105', 'procedimento' => 'DOSAGEM DE ANTIGENO PROSTATICO ESPECIFICO (PSA)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010201', 'procedimento' => 'DOSAGEM DE BILIRRUBINA TOTAL E FRACOES', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010210', 'procedimento' => 'DOSAGEM DE CALCIO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010228', 'procedimento' => 'DOSAGEM DE CALCIO IONIZAVEL', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070158', 'procedimento' => 'DOSAGEM DE CARBAMAZEPINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010260', 'procedimento' => 'DOSAGEM DE CLORETO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010279', 'procedimento' => 'DOSAGEM DE COLESTEROL HDL', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010287', 'procedimento' => 'DOSAGEM DE COLESTEROL LDL', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010295', 'procedimento' => 'DOSAGEM DE COLESTEROL TOTAL', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030121', 'procedimento' => 'DOSAGEM DE COMPLEMENTO C3', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030130', 'procedimento' => 'DOSAGEM DE COMPLEMENTO C4', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010317', 'procedimento' => 'DOSAGEM DE CREATININA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010325', 'procedimento' => 'DOSAGEM DE CREATINOFOSFOQUINASE (CPK)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010368', 'procedimento' => 'DOSAGEM DE DESIDROGENASE LATICA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010384', 'procedimento' => 'DOSAGEM DE FERRITINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010392', 'procedimento' => 'DOSAGEM DE FERRO SERICO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010422', 'procedimento' => 'DOSAGEM DE FOSFATASE ALCALINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010465', 'procedimento' => 'DOSAGEM DE GAMA-GLUTAMIL-TRANSFERASE (GAMA GT)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010473', 'procedimento' => 'DOSAGEM DE GLICOSE', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060217', 'procedimento' => 'DOSAGEM DE GONADOTROFINA CORIONICA HUMANA (HCG, BETA HCG)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060250', 'procedimento' => 'DOSAGEM DE HORMONIO TIREOESTIMULANTE (TSH)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060268', 'procedimento' => 'DOSAGEM DE INSULINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010538', 'procedimento' => 'DOSAGEM DE LACTATO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202070255', 'procedimento' => 'DOSAGEM DE LITIO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010562', 'procedimento' => 'DOSAGEM DE MAGNESIO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010600', 'procedimento' => 'DOSAGEM DE POTASSIO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030202', 'procedimento' => 'DOSAGEM DE PROTEINA C REATIVA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010619', 'procedimento' => 'DOSAGEM DE PROTEINAS TOTAIS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010627', 'procedimento' => 'DOSAGEM DE PROTEINAS TOTAIS E FRACOES', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010635', 'procedimento' => 'DOSAGEM DE SODIO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060381', 'procedimento' => 'DOSAGEM DE TIROXINA LIVRE (T4 LIVRE)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010643', 'procedimento' => 'DOSAGEM DE TRANSAMINASE GLUTAMICO-OXALACETICA (TGO)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010651', 'procedimento' => 'DOSAGEM DE TRANSAMINASE GLUTAMICO-PIRUVICA(TGP)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010678', 'procedimento' => 'DOSAGEM DE TRIGLICERIDEOS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060390', 'procedimento' => 'DOSAGEM DE TRIIODOTIRONINA (T3)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010694', 'procedimento' => 'DOSAGEM DE UREIA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202080145', 'procedimento' => 'EXAME MICROBIOLOGICO A FRESCO (DIRETO)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020380', 'procedimento' => 'HEMOGRAMA COMPLETO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030474', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTIESTREPTOLISINA O (ASLO)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030563', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTIMITOCONDRIA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030580', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTIMUSCULO LISO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030598', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTINUCLEO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030679', 'procedimento' => 'PESQUISA DE ANTICORPOS CONTRA O VIRUS DA HEPATITE C (ANTI-HCV)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030768', 'procedimento' => 'PESQUISA DE ANTICORPOS IGG ANTITOXOPLASMA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030814', 'procedimento' => 'PESQUISA DE ANTICORPOS IGG CONTRA O VIRUS DA RUBEOLA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030830', 'procedimento' => 'PESQUISA DE ANTICORPOS IGG CONTRA O VIRUS EPSTEIN-BARR', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030873', 'procedimento' => 'PESQUISA DE ANTICORPOS IGM ANTITOXOPLASMA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030911', 'procedimento' => 'PESQUISA DE ANTICORPOS IGM CONTRA O VIRUS DA HEPATITE A (HAV-IGG)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030920', 'procedimento' => 'PESQUISA DE ANTICORPOS IGM CONTRA O VIRUS DA RUBEOLA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030946', 'procedimento' => 'PESQUISA DE ANTICORPOS IGM CONTRA O VIRUS EPSTEIN-BARR', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030970', 'procedimento' => 'PESQUISA DE ANTIGENO DE SUPERFICIE DO VIRUS DA HEPATITE B (HBSAG)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020410', 'procedimento' => 'PESQUISA DE CELULAS LE', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202031012', 'procedimento' => 'PESQUISA DE FATOR REUMATOIDE (WAALER-ROSE)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202120082', 'procedimento' => 'PESQUISA DE FATOR RH (INCLUI D FRACO)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202040097', 'procedimento' => 'PESQUISA DE LEUCOCITOS NAS FEZES', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202040127', 'procedimento' => 'PESQUISA DE OVOS E CISTOS DE PARASITAS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202040135', 'procedimento' => 'PESQUISA DE ROTAVIRUS NAS FEZES', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020495', 'procedimento' => 'PROVA DE RETRACAO DO COAGULO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202031128', 'procedimento' => 'TESTE FTA-ABS IGG P/ DIAGNOSTICO DA SIFILIS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202031136', 'procedimento' => 'TESTE FTA-ABS IGM P/ DIAGNOSTICO DA SIFILIS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202050050', 'procedimento' => 'CONTAGEM DE ADDIS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010031', 'procedimento' => 'DETERMINACAO DE CROMATOGRAFIA DE AMINOACIDOS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060012', 'procedimento' => 'DETERMINACAO DE INDICE DE TIROXINA LIVRE', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202010350', 'procedimento' => 'DOSAGEM DE DESIDROGENASE GLUTAMICA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202060373', 'procedimento' => 'DOSAGEM DE TIROXINA (T4)', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030610', 'procedimento' => 'PESQUISA DE ANTICORPOS ANTIPLASMODIOS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202030652', 'procedimento' => 'PESQUISA DE ANTICORPOS CONTRA HISTOPLASMA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020401', 'procedimento' => 'PESQUISA DE ATIVIDADE DO COFATOR DE RISTOCETINA', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020428', 'procedimento' => 'PESQUISA DE CORPUSCULOS DE HEINZ', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202040062', 'procedimento' => 'PESQUISA DE EOSINOFILOS', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202080234', 'procedimento' => 'PESQUISA DE TREPONEMA PALLIDUM', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202040178', 'procedimento' => 'PESQUISA DE TROFOZOITAS NAS FEZES', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE'],
            ['codigo' => '0202020509', 'procedimento' => 'PROVA DO LACO', 'idade' => '0 MESES - 130 ANOS', 'limite' => 'SEM LIMITE']
        ]);

        $dados = [
            ['nome' => '1A', 'valor' => 8.00],
            ['nome' => '1B', 'valor' => 16.00],
            ['nome' => '1C', 'valor' => 24.00],
            ['nome' => '2A', 'valor' => 32.00],
            ['nome' => '2B', 'valor' => 42.00],
            ['nome' => '2C', 'valor' => 50.00],
            ['nome' => '3A', 'valor' => 69.00],
            ['nome' => '3B', 'valor' => 88.00],
            ['nome' => '3C', 'valor' => 100.00],
            ['nome' => '4A', 'valor' => 120.00],
            ['nome' => '4B', 'valor' => 132.00],
            ['nome' => '4C', 'valor' => 148.00],
            ['nome' => '5A', 'valor' => 160.00],
            ['nome' => '5B', 'valor' => 172.00],
            ['nome' => '5C', 'valor' => 184.00],
            ['nome' => '6A', 'valor' => 200.00],
            ['nome' => '6B', 'valor' => 220.00],
            ['nome' => '6C', 'valor' => 240.00],
            ['nome' => '7A', 'valor' => 260.00],
            ['nome' => '7B', 'valor' => 280.00],
            ['nome' => '7C', 'valor' => 340.00],
            ['nome' => '8A', 'valor' => 368.00],
            ['nome' => '8B', 'valor' => 384.00],
            ['nome' => '8C', 'valor' => 408.00],
            ['nome' => '9A', 'valor' => 436.00],
            ['nome' => '9B', 'valor' => 476.00],
            ['nome' => '9C', 'valor' => 524.00],
            ['nome' => '10A', 'valor' => 560.00],
            ['nome' => '10B', 'valor' => 608.00],
            ['nome' => '10C', 'valor' => 676.00],
            ['nome' => '11A', 'valor' => 716.00],
            ['nome' => '11B', 'valor' => 784.00],
            ['nome' => '11C', 'valor' => 860.00],
            ['nome' => '12A', 'valor' => 892.00],
            ['nome' => '12B', 'valor' => 960.00],
            ['nome' => '12C', 'valor' => 1_176.00],
            ['nome' => '13A', 'valor' => 1_320.00],
            ['nome' => '13B', 'valor' => 1_420.00],
            ['nome' => '13C', 'valor' => 1_570.00],
            ['nome' => '14A', 'valor' => 1_900.00],
            ['nome' => '14B', 'valor' => 1_900.00],
            ['nome' => '14C', 'valor' => 2_100.00],
        ];

        DB::table('tabelas')->insert($dados);

        $taxas = [
            ['descricao' => 'Manutenção de equipamentos médicos', 'valor' => '150.00'],
            ['descricao' => 'Esterilização de materiais', 'valor' => '50.00'],
            ['descricao' => 'Manutenção de infraestrutura', 'valor' => '100.00'],
            ['descricao' => 'Agendamento prioritário', 'valor' => '30.00'],
            ['descricao' => 'Reagendamento fora do prazo', 'valor' => '20.00'],
            ['descricao' => 'Consulta administrativa (documentos ou atestados)', 'valor' => '50.00'],
            ['descricao' => 'Cancelamento tardio (menos de 24h)', 'valor' => '40.00'],
            ['descricao' => 'Materiais descartáveis', 'valor' => '25.00'],
            ['descricao' => 'Sedação/anestesia', 'valor' => '200.00'],
            ['descricao' => 'Uso de sala de procedimentos (prolongado)', 'valor' => '300.00'],
            ['descricao' => 'Avaliação pré-procedimento', 'valor' => '100.00'],
            ['descricao' => 'Ultrassom portátil', 'valor' => '500.00'],
            ['descricao' => 'Monitor multiparamétrico', 'valor' => '250.00'],
            ['descricao' => 'Desfibrilador', 'valor' => '300.00'],
            ['descricao' => 'Bombas de infusão', 'valor' => '150.00'],
            ['descricao' => 'Equipamentos de fisioterapia', 'valor' => '100.00'],
            ['descricao' => 'Equipamentos de fototerapia', 'valor' => '200.00'],
            ['descricao' => 'Sala de pequenos procedimentos', 'valor' => '500.00'],
            ['descricao' => 'Sala de consulta', 'valor' => '400.00'],
            ['descricao' => 'Sala cirúrgica', 'valor' => '1500.00'],
            ['descricao' => 'Cadeira odontológica (parceiros)', 'valor' => '350.00'],
            ['descricao' => 'Manutenção de ultrassom', 'valor' => '150.00'],
            ['descricao' => 'Calibração de equipamentos', 'valor' => '75.00'],
            ['descricao' => 'Exames laboratoriais (coleta e processamento)', 'valor' => '50.00'],
            ['descricao' => 'Exames de imagem (uso de contraste)', 'valor' => '100.00'],
            ['descricao' => 'Materiais descartáveis em cirurgias', 'valor' => '200.00'],
            ['descricao' => 'Uso de equipamentos adicionais (endoscopia, laparoscopia)', 'valor' => '200.00'],
            ['descricao' => 'Anestesia local', 'valor' => '150.00'],
            ['descricao' => 'Anestesia geral', 'valor' => '500.00'],
            ['descricao' => 'Monitoramento anestésico', 'valor' => '300.00'],
            ['descricao' => 'Instrumentador cirúrgico', 'valor' => '200.00'],
            ['descricao' => 'Enfermeiro(a) auxiliar', 'valor' => '200.00'],
        ];

        // Insere os dados na tabela 'taxas'
        DB::table('taxas')->insert($taxas);
    }
}
